[commit_types]
feat = { changelog_title = "Features", bump = "minor" }
fix = { changelog_title = "Bug Fixes", bump = "patch" }
chore = { changelog_title = "Miscellaneous", omit_from_changelog = true }
docs = { changelog_title = "Documentation", omit_from_changelog = true }

[bump_profiles.tauri]
pre_bump_hooks = [
    "cargo check",
    "npm run build",
    "echo 'Updating version to {{version}}'",
    # Обновляем Cargo.toml
    "sed -i 's/^version = .*/version = \"{{version}}\"/' src-tauri/Cargo.toml",
    # Обновляем package.json если используется
    "npm version {{version}} --no-git-tag-version || true",
    # Проверяем что tauri.conf.json указывает на корректный источник версии
    "cargo check"
]
post_bump_hooks = [
    "git push",
    "git push --tags"
]
