[commit_types]
feat = { changelog_title = "Features", bump = "minor" }
fix = { changelog_title = "Bug Fixes", bump = "patch" }
chore = { changelog_title = "Miscellaneous", omit_from_changelog = true }
docs = { changelog_title = "Documentation", omit_from_changelog = true }

[bump_profiles.tauri]
pre_bump_hooks = [
    "cd src-tauri && cargo check",
    "npm run build",
    "echo 'Updating version to {{version}}'",
    # Обновляем Cargo.toml (PowerShell команда для Windows)
    "powershell -Command \"(Get-Content src-tauri/Cargo.toml) -replace '^version = .*', 'version = \\\"{{version}}\\\"' | Set-Content src-tauri/Cargo.toml\"",
    # Синхронизируем версии между файлами
    "npm run sync-version",
    # Проверяем что все файлы обновлены корректно
    "cd src-tauri && cargo check"
]
post_bump_hooks = [
    "git push",
    "git push --tags"
]
