[commit_types]
feat = { changelog_title = "Features", bump = "minor" }
fix = { changelog_title = "Bug Fixes", bump = "patch" }
chore = { changelog_title = "Miscellaneous", omit_from_changelog = true }
docs = { changelog_title = "Documentation", omit_from_changelog = true }

[bump_profiles.tauri]
pre_bump_hooks = [
    "cd src-tauri && cargo check",
    "npm run build",
    "echo 'Updating version to {{version}}'",
    # Обновляем версию через Node.js скрипт
    "node -e \"const fs=require('fs'); const content=fs.readFileSync('src-tauri/Cargo.toml','utf8'); const updated=content.replace(/^version = .*/m, 'version = \\\"{{version}}\\\"'); fs.writeFileSync('src-tauri/Cargo.toml', updated);\"",
    # Синхронизируем версии между файлами
    "npm run sync-version",
    # Проверяем что все файлы обновлены корректно
    "cd src-tauri && cargo check"
]
post_bump_hooks = [
    "git push origin main",
    "git push origin --tags"
]
