[build]
# Исключаем папку examples из сборки по умолчанию
exclude = ["examples"]

[rust-analyzer]
# Дополнительные настройки для rust-analyzer
cargo.excludeDirs = ["examples"]
files.excludeDirs = ["examples", "target", ".cargo"]



