name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Stylelint
        run: npx stylelint "src/**/*.css"
      - name: Prettier check
        run: npx prettier --check .
